import { appFbIcon } from './fb';
import { appGooglePinIcon } from './google-pin';
import { appGoogleIcon } from './google';
import { appInstaIcon } from './insta';
import { appMailRuIcon } from './mail.ru';
import { appOkIcon } from './ok';
import { appTelegramIcon } from './telegram';
import { appVkIcon } from './vk';
import { appYandexPinIcon } from './yandex-pin';
import { appYandexIcon } from './yandex';
export const socialIcons = [appFbIcon, appGooglePinIcon, appGoogleIcon, appInstaIcon, appMailRuIcon, appOkIcon, appTelegramIcon, appVkIcon, appYandexPinIcon, appYandexIcon];
